### ISSUE TITLE
Bad conversion of static const var = {}

### ISSUE THREAD

**Issue by 19h** [jameysharp/corrode#61] opened 2016-08-29 00:52 UTC
Hey,

there seems to be a pretty big issue with `static const var = {}` in Corrode.

Input:

```
static const D = {0x78a3, 0x1359, 0x4dca, 0x75eb, 0xd8ab, 0x4141, 0x0a4d, 0x0070, 0xe898, 0x7779, 0x4079, 0x8cc7, 0xfe73, 0x2b6f, 0x6cee, 0x5203};
```

Output:

```
static D : *mut isize = 0x78a3i32 as (*mut isize);
```

**Comment by jameysharp** [comment] 2016-09-07 19:25
Sorry for the delay getting back to you! I still haven't figured out how to get GitHub to e-mail me when new issues are filed. :frowning:

Did you mean `D[]` rather than just `D`? If you aren't trying to declare an array, then that's a weird (although legal) declaration.

If you did want an array, then this is a duplicate of bug #52, and we should close this one and follow that one.

I can't reproduce the output you're seeing as-is; I get:

``` rust
static D : i32 = 0x78a3i32;
```

Which matches what GCC compiles that to, and I think is correct.

**Comment by jameysharp** [comment] 2016-11-28 07:27
Since I haven't heard back from you, I'm going to assume you did mean `D[]` and that this is a duplicate of #52. Which I'm working on!

**Closed as completed by jameysharp** 2016-11-28 07:27 UTC
Labels: duplicate
