### ISSUE TITLE
implement typedef for function types

### ISSUE THREAD

**Issue by meagon** [jameysharp/corrode#53] opened 2016-07-30 17:55 UTC
I got this error

```
("/usr/include/libio.h": line 360): illegal undefined type; check whether a real C compiler accepts this:
    __io_read_fn

```

but  found

```
335    typedef __ssize_t __io_read_fn (void *__cookie, char *__buf, size_t __nbytes);
```

**Comment by jameysharp** [comment] 2016-07-31 05:04
OK, placing the following two lines in a file and running corrode over it will trigger this bug:

``` c
#define _GNU_SOURCE
#include <libio.h>
```

Simplifying further, so will this source file:

``` c
typedef void typ (void);
typ var;
```

But not this one:

``` c
typedef int typ;
typ var;
```

So that's good evidence. And in fact the problem is that `interpretDeclarations` doesn't yet handle typedefs for function types, only for function pointer types. For example, this works just fine:

``` c
typedef void (*typ) (void);
typ var;
```

The troublesome line is the one which pattern-matches on `(Just (CTypedef _), False, _)`: that `False` in the middle insists that the type not be a function type.

The reason I didn't handle the `True` case is that Rust doesn't have a distinction between function types and function pointer types, so I didn't want to encode that distinction in the internal `CType` representation. But clearly we need to carry that information through typedefs, so we have to fix it somehow.

For the moment, I've committed a tiny patch to check for this case and report the correct "Corrode doesn't handle this yet" error message on the original typedef, rather than the "illegal undefined type" error message later when trying to use the type. Unfortunately that means we once again can't translate things using `stdio.h`. :cry:

I'd welcome proposals or pull requests fixing this! Otherwise I'll probably figure it out sooner or later, because it's going to bother me now.

**Closed as completed** 2016-09-17 13:24 UTC
