### ISSUE TITLE
optimization level mistaken for output file

### ISSUE THREAD

**Issue by flip111** [jameysharp/corrode#127] opened 2017-03-14 09:22 UTC
When you put `corrode -o1` you get error `cc1: error: output filename specified twice`, i know normally optimization level is with capital O, but gcc doesn't complain about this, but corrode has a problem here.

**Comment by jameysharp** [comment] 2017-04-05 07:53
Thanks for your report! Unfortunately, I can't confirm this. If I run `gcc -o1 -c test.c`, I get an object file written to the file named `1`. So as far as I can tell, even with GCC you really do need to use a capital-O to request a particular optimization level.

I'm closing this issue (as far as I can tell, it's not a bug) but feel free to re-open if you disagree. Thanks!

**Closed as completed by jameysharp** 2017-04-05 07:53 UTC
