### ISSUE TITLE
Pointer arithmetic are off

### ISSUE THREAD

**Issue by tko** [jameysharp/corrode#89] opened 2016-11-07 21:50 UTC
The relatively normal C construct of `nbytes = endpointer - startpointer` seems to be translated incorrectly and the end result is divided by pointer size.
```C
#include <stdio.h>
#include <stddef.h>
ptrdiff_t test(int n) {
  const char buf[] = "hello world";
  const char *start = buf;
  const char *end = &buf[n];
  return end - start;
}

int main() {
  int i;
  for (i = 0 ; i < 11; i++) {
    printf("%d=%d\n", i, test(i));
  }
  return 0;
}
```
Result when compiled as C:
```
0=0
1=1
2=2
3=3
4=4
5=5
6=6
7=7
8=8
9=9
10=10
```
Result when compiled as Rust:
```
0=0
1=0
2=0
3=0
4=0
5=0
6=0
7=0
8=1
9=1
10=1
```
Generated code
```rust
pub unsafe extern fn test(mut n : i32) -> isize {
    let mut buf : *const u8 = b"hello world\0".as_ptr();
    let mut start : *const u8 = buf;
    let mut end
        : *const u8
        = &*buf.offset(n as (isize)) as (*const u8);
    (end as (isize)).wrapping_sub(
        start as (isize)
    ) / std::mem::size_of::<*const u8>() as (isize)
}
```
Seems to me the division should be `size_of::<u8>` instead.

**Comment by jameysharp** [comment] 2016-11-08 01:27
Yeah, I botched that, didn't I? Looks like I committed c66e8bb shortly after midnight, which maybe explains how I got that wrong. :smile:

Would you like to fix it? If you look at the diff in that commit, you'll see that the problem is that I used the expression `compatiblePtr (resultType lhs) (resultType rhs)` directly as the type to use with `size_of`. Instead we should use something like:

``` haskell
ptrTo <- case compatiblePtr (resultType lhs) (resultType rhs) of
    IsPtr _ ptrTo -> return ptrTo
    _ -> badSource expr "pointer subtraction of incompatible pointers"
let size = rustSizeOfType (toRustType ptrTo)
```

If you could check that that change actually fixes the bug for you, then submit a pull request, I'd appreciate it!

**Closed as completed** 2016-11-11 20:47 UTC
